logging:

#日志配置部分

   file: logs/my.log
   level:
       root: info
spring:
   redis:
        # 单机版配置
       host: 120.24.237.131
       port: 6379
       password: 123456
       database: 0
       timeout: 3000
       pool:
      # 连接池最大连接数（使用负值表示没有限制）
          max-active: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1
      # 连接池中的最大空闲连接
          max-idle: 8
      # 连接池中的最小空闲连接
          min-idle: 0
     #  cluster:
      #   nodes:


        #redis 集群配置
   #   cluster:
    #    nodes:
    #      - 120.76.143.217:7001
    #      - 120.76.143.217:7002
    #      - 120.76.143.217:7003
    #      - 120.76.143.217:7004
    #      - 120.76.143.217:7005
     #     - 120.76.143.217:7006

# default-store in spring session. it will be set in redis only outside.
   session:
       store-type: redis


   datasource:
       url: jdbc:mysql://120.24.237.131:3306/waterworks_platform?useUnicode=true&characterEncoding=utf-8&useSSL=true
       username: root
       password: 123456
        # 使用druid数据源
       type: com.alibaba.druid.pool.DruidDataSource
       driver-class-name: com.mysql.jdbc.Driver

   mvc:
     view:
       prefix: /WEB-INF/jsp/
       suffix: .jsp

   data:
      mongodb:
        host: 120.24.237.131
        port: 27017
      #  username: dev_xxx
      #  password: dev_xxxx
        database: test
mybatis:
  #*Mapper.java可以随便放，只要和mapper.xml对应上就行

   type-aliases-package: com.waterworks.repository.entity
   mapper-locations: com/waterworks.repository.mapper/xml/*.xml



#这个插件是mybatis的分页查询

pagehelper:
   helperDialect: mysql
   reasonable: true
   supportMethodsArguments: true
   params: count=countSql

