logging:

#日志配置部分

   file: logs/my.log
   level:
       root: info
spring:
   datasource:
       url: jdbc:mysql://120.24.237.131:3306/waterworks_platform?useUnicode=true&characterEncoding=utf-8&useSSL=true
       username: root
       password: 123456
        # 使用druid数据源
       type: com.alibaba.druid.pool.DruidDataSource
       driver-class-name: com.mysql.jdbc.Driver


   # default-store in spring session. it will be set in redis only outside.
   session:
        store-type: none

   mvc:
     view:
       prefix: /WEB-INF/jsp/
       suffix: .jsp
mybatis:
  #*Mapper.java可以随便放，只要和mapper.xml对应上就行
   mapper-locations: classpath:mappering/*.xml
   type-aliases-package: com.main.wregulator.dao.mapper
   #type-aliases-package: com.bandaoti.demo.backend.entity

#这个插件是mybatis的分页查询

pagehelper:
   helperDialect: mysql
   reasonable: true
   supportMethodsArguments: true
   params: count=countSql

